server:
    port: 9093
spring:
  application:
    name: attendance-service
eureka:
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadata-map:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port})}
  client:
    region: default
    registry-fetch-interval-seconds: 5
    service-url:
       defaultZone: http://localhost:8761/eureka/
      

        
