
spring:
  application:
    name: EmployeeRESTAPI

  datasource:
    url: jdbc:mysql://localhost:3306/EmployeeDBOFS
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.eclipse.persistence.platform.database.MySQLPlatform
    show-sql: true

  devtools:
    livereload:
      port: 8082

server:
  port: 8089
